[build]
  command = "npm run build"
  publish = "dist"

[context.production.environment]
  NODE_ENV = "production"

[template.environment]
  META_TITLE = ""
  META_URL = ""
  META_DESC = ""
  META_LANG = "en"
  META_EMAIL = ""
  META_PHONE = ""

[[redirects]]
  from = "*"
  to = "/404"
  status = 404

[[plugins]]
package = "netlify-plugin-a11y"
  [plugins.inputs]
  # required config
  checkPaths = ['/index.html'] # you can give an array of directories or paths to html files, that you want to run a11y checks on
  # optional config
  resultMode = "warn" # is "error" by default
